apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: groupchat
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: groupchat2024
  JWT_SECRET: gruopChat-secret-key-2026-eafit-telematica-st0263
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
